CREATE OR REPLACE DATABASE STUDENTDB_CLONE
CLONE STUDENTDB;

-- when we clone the database it will not going to clone internal stage and external table.

CREATE or REPLACE TABLE STUDENT_SCORES_CLONE CLONE STUDENT_SCORES;

SELECT * FROM INFORMATION_SCHEMA.TABLE_STORAGE_METRICS WHERE TABLE_CATALOG= 'STUDENTDB';

TRUNCATE TABLE STUDENT_SCORES;

SELECT * FROM STUDENT_SCORES;

SELECT * FROM STUDENT_SCORES_CLONE;

CREATE OR REPLACE TABLE BACKUP_STUDENT_SCORES CLONE STUDENT_SCORES AT (OFFSET => -06*10);

SELECT * FROM BACKUP_STUDENT_SCORES;

ALTER TABLE STUDENT_SCORES SWAP WITH BACKUP_STUDENT_SCORES;
