CREATE OR REPLACE DATABASE CUSTOMER_GOV_DB;
CREATE OR REPLACE SCHEMA CUSTOMER_SEC;

USE DATABASE CUSTOMER_GOV_DB;
USE SCHEMA CUSTOMER_SEC;

-- GRANT ACCESS OF DB, SCHEMA TO OTHER ROLE
USE ROLE SECURITYADMIN;

CREATE OR REPLACE ROLE CALL_CENTER_AGENT;

GRANT ROLE CALL_CENTER_AGENT TO USER GOJO;

GRANT USAGE ON DATABASE CUSTOMER_GOV_DB TO ROLE CALL_CENTER_AGENT;
GRANT USAGE ON SCHEMA CUSTOMER_GOV_DB.CUSTOMER_SEC TO ROLE CALL_CENTER_AGENT;
GRANT SELECT ON ALL TABLES IN SCHEMA CUSTOMER_GOV_DB. CUSTOMER_SEC TO ROLE CALL_CENTER_AGENT;


CREATE OR REPLACE TABLE CUSTOMER_MASTER (
CUSTOMER_ID NUMBER,
FIRST_NAME STRING,
LAST_NAME STRING,
EMAIL STRING,
PHONE_NUMBER STRING,
CREDIT_CARD_NUMBER NUMBER,
COUNTRY STRING,
CREATED_DATE DATE
);

INSERT INTO CUSTOMER_MASTER
SELECT
    SEQ4() + 1 AS CUSTOMER_ID,
    'Customer_' || SEQ4() AS FIRST_NAME,
    'User_' || SEQ4() AS LAST_NAME,
    'customer' || SEQ4() || '@example. com' AS EMAIL,
    '+91-' || (900000000 + UNIFORM(1, 999999999, RANDOM())) AS PHONE_NUMBER,
    '411111111111' || LPAD(SEQ4()::STRING, 4, '0') AS CREDIT_CARD_NUMBER,
    CASE
    WHEN SEQ4() % 3 = 0 THEN 'INDIA'
    WHEN SEQ4() % 3 = 1 THEN 'USA'
    ELSE 'GERMANY'
    END AS COUNTRY,
    CURRENT_DATE - UNIFORM(1, 365, RANDOM()) AS CREATED_DATE
    FROM TABLE(GENERATOR(ROWCOUNT => 100));


SELECT * from CUSTOMER_MASTER;

CREATE OR REPLACE MASKING POLICY MASK_CUSTOMER_PII
AS (VAL STRING)
    RETURNS STRING ->
        CASE
            WHEN CURRENT_ROLE() IN ('ACCOUNTADMIN' ) THEN VAL
            ELSE ' *** MASKED *** '
        END;


CREATE OR REPLACE MASKING POLICY MASK_CUSTOMER_PH AS (VAL NUMBER)
    RETURNS NUMBER ->
        CASE WHEN CURRENT_ROLE() IN ('ACCOUNTADMIN' ) THEN VAL
        ELSE regexp_replace (VAL, substring (VAL, 1, 12), '111111')
    END;

-- assigne masking policy

ALTER TABLE CUSTOMER_MASTER
MODIFY COLUMN EMAIL SET MASKING POLICY MASK_CUSTOMER_PII;

ALTER TABLE CUSTOMER_MASTER
MODIFY COLUMN PHONE_NUMBER SET MASKING POLICY MASK_CUSTOMER_PII;

ALTER TABLE CUSTOMER_MASTER
MODIFY COLUMN CREDIT_CARD_NUMBER SET MASKING POLICY MASK_CUSTOMER_PH;

USE ROLE CALL_CENTER_AGENT;

SELECT CURRENT_USER();

Select * from CUSTOMER_MASTER;

--- Unset the masking policy
ALTER TABLE CUSTOMER_MASTER MODIFY COLUMN EMAIL UNSET MASKING POLICY;
ALTER TABLE CUSTOMER_MASTER MODIFY COLUMN PHONE_NUMBER UNSET MASKING POLICY;
ALTER TABLE CUSTOMER_MASTER MODIFY COLUMN CREDIT_CARD_NUMBER UNSET MASKING POLICY;

--- Now let's do it by TAG
CREATE OR REPLACE TAG CUSTOMER_SENSITIVE_TAG ALLOWED_VALUES 'PII Varchar', 'PII Number'
COMMENT = 'Tag to classify sensitive customer PII data';

-- Associate Masking policy
ALTER TAG CUSTOMER_SENSITIVE_TAG SET MASKING POLICY MASK_CUSTOMER_PII;

-- assign tags to customer

ALTER TABLE CUSTOMER_MASTER MODIFY COLUMN EMAIL SET TAG CUSTOMER_SENSITIVE_TAG = 'PII Varchar';
ALTER TABLE CUSTOMER_MASTER MODIFY COLUMN PHONE_NUMBER SET TAG CUSTOMER_SENSITIVE_TAG = 'PII Varchar';
ALTER TABLE CUSTOMER_MASTER MODIFY COLUMN CREDIT_CARD_NUMBER SET TAG CUSTOMER_SENSITIVE_TAG = 'PII Number';

SELECT * FROM CUSTOMER_MASTER;


ALTER TAG CUSTOMER_SENSITIVE_TAG UNSET MASKING POLICY MASK_CUSTOMER_PII;

CREATE OR REPLACE MASKING POLICY MASK_CUSTOMER_PII
    AS (VAL STRING)
        RETURNS STRING ->
        CASE
            WHEN CURRENT_ROLE() IN ('ACCOUNTADMIN') THEN VAL
            WHEN SYSTEM$GET_TAG_ON_CURRENT_COLUMN('CUSTOMER_SENSITIVE_TAG') = 'PII Varchar' THEN ' *** MASKED *** '
        END;

CREATE OR REPLACE MASKING POLICY MASK_CUSTOMER_PH AS (VAL NUMBER)
    RETURNS NUMBER ->
        CASE WHEN CURRENT_ROLE() IN ('ACCOUNTADMIN' ) THEN VAL
            WHEN SYSTEM$GET_TAG_ON_CURRENT_COLUMN('CUSTOMER_SENSITIVE_TAG') = 'PII Number' THEN regexp_replace(VAL,substring(VAL, 1, 12), '000000')
        END;


-- now in final we will associate this policy of same data type
ALTER TAG CUSTOMER_SENSITIVE_TAG SET MASKING POLICY MASK_CUSTOMER_PII
, MASKING POLICY MASK_CUSTOMER_PH;


USE ROLE CALL_CENTER_AGENT;

SELECT * FROM CUSTOMER_MASTER;

Select * from TABLE(INFORMATION_SCHEMA.TAG_REFERENCES('CUSTOMER_MASTER','table') );
