CREATE OR REPLACE NOTIFICATION INTEGRATION error_notification_int
TYPE = QUEUE
DIRECTION = OUTBOUND
NOTIFICATION_PROVIDER = AWS_SNS
ENABLED = TRUE
AWS_SNS_TOPIC_ARN = 'arn:aws:sns:ap-southeast-1:889486283825:error_success_notification_topic'
AWS_SNS_ROLE_ARN = 'arn:aws:iam::889486283825:role/error_notification_role';

DESC NOTIFICATION INTEGRATION error_notification_int;

CREATE or REPLACE TABLE PRODUCTS(
PRODUCTID INT,
PRODUCTNAME VARCHAR,
COLOR VARCHAR,
PRICE INT);


CREATE OR REPLACE TASK ROOTTASK
WAREHOUSE = COMPUTE_WH
SCHEDULE = '1 MINUTE'
SUCCESS_INTEGRATION = error_notification_int
-- ERROR_INTEGRATION
AS
INSERT INTO PRODUCTS VALUES(1,'IPHONE','BLACK',500000); 

SHOW TASKS;

-- BY DEFAULT TASK CREATE IN SUSPENDED MODE 
ALTER TASK ROOTTASK RESUME;

ALTER TASK ROOTTASK SUSPEND;

SHOW NOTIFICATION INTEGRATIONS;

SELECT * FROM TABLE(INFORMATION_SCHEMA.TASK_HISTORY(
TASK_NAME => 'ROOTTASK'
));

SELECT * FROM PRODUCTS;
