SHOW STAGES;

lIST @STAGE_AWS_STU_V1;

CREATE OR REPLACE EXTERNAL TABLE STUDENT_EXTERNAL
WITH LOCATION = @STAGE_AWS_STU_V1
PATTERN = '.*students-performance-v2\.csv'
FILE_FORMAT = (TYPE = CSV SKIP_HEADER = 1 FIELD_OPTIONALLY_ENCLOSED_BY = '"');

SELECT * FROM STUDENT_EXTERNAL;

SELECT VALUE:c1::NUMBER AS ID , VALUE FROM STUDENT_EXTERNAL;

CREATE OR REPLACE EXTERNAL TABLE STUDENT_EXTERNAL_V2(
MATH_SCORE INT AS (VALUE:c1::NUMBER),
ENGLISH_SCORE INT AS (VALUE:c2::NUMBER),
BIO_SCORE INT AS (VALUE:c3::NUMBER),
PHYSICS_SCORE INT AS (VALUE:c4::NUMBER))
LOCATION = @STAGE_AWS_STU_V1
PATTERN = '.*students-performance-v2\.csv'
FILE_FORMAT = (TYPE = CSV SKIP_HEADER = 1 FIELD_OPTIONALLY_ENCLOSED_BY = '"');

SELECT * FROM STUDENT_EXTERNAL_V2;

SELECT * , METADATA$FILENAME FROM STUDENT_EXTERNAL_V2;