CREATE DATABASE PAQ_INFER_DB;

CREATE SCHEMA PAQ_INFER_SCHEMA;

CREATE OR REPLACE FILE FORMAT PAQT_TYPE 
TYPE = PARQUET;

CREATE OR REPLACE STORAGE INTEGRATION AWS_STUDENT_PAQT
Type = EXTERNAL_STAGE
STORAGE_PROVIDER = S3
ENABLED = TRUE   
STORAGE_AWS_ROLE_ARN = 'arn:aws:iam::889486283825:role/s3_parq_snowflake'
STORAGE_ALLOWED_LOCATIONS = ('s3://student-parquet/stduent_data/');

DESC STORAGE INTEGRATION AWS_STUDENT_PAQT;

CREATE OR REPLACE STAGE STUDENT_PRQT_STAGE
URL='s3://student-parquet/stduent_data/'
STORAGE_INTEGRATION = AWS_STUDENT_PAQT
FILE_FORMAT = (FORMAT_NAME = PAQT_TYPE);

LIST @STUDENT_PRQT_STAGE;

SELECT * FROM @STUDENT_PRQT_STAGE;

SELECT * FROM TABLE(
INFER_SCHEMA(
LOCATION => '@STUDENT_PRQT_STAGE',
FILE_FORMAT => 'PAQT_TYPE',
IGNORE_CASE => TRUE
));

CREATE OR REPLACE TABLE STUDENT_DATA USING TEMPLATE(
SELECT ARRAY_AGG(OBJECT_CONSTRUCT(*))
FROM TABLE(
INFER_SCHEMA(
LOCATION => '@STUDENT_PRQT_STAGE',
FILE_FORMAT => 'PAQT_TYPE',
IGNORE_CASE => TRUE
)));

SHOW TABLES;

COPY INTO STUDENT_DATA FROM @STUDENT_PRQT_STAGE
FILE_FORMAT = 'PAQT_TYPE',
MATCH_BY_COLUMN_NAME= CASE_INSENSITIVE;

SELECT * FROM STUDENT_DATA;

SELECT COUNT(*) FROM STUDENT_DATA;
