create database employeeDB;

create schema employeeSchema;

Create or replace storage Integration employee_integration
Type = EXTERNAL_STAGE
STORAGE_PROVIDER = S3
ENABLED = TRUE   
STORAGE_AWS_ROLE_ARN = 'arn:aws:iam::889486283825:role/employee_sdc_role'
STORAGE_ALLOWED_LOCATIONS = ('s3://empoyee-scd-data/employee_data/');

DESC STORAGE INTEGRATION employee_integration;

select "property", "property_value" from TABLE(RESULT_SCAN(LAST_QUERY_ID()))
where "property" = 'STORAGE_AWS_IAM_USER_ARN' or "property" = 'STORAGE_AWS_EXTERNAL_ID';

CREATE OR REPLACE FILE FORMAT ingest_csv_data
TYPE = CSV
FIELD_DELIMITER = ','
SKIP_HEADER = 1
FIELD_OPTIONALLY_ENCLOSED_BY = '"';

SHOW FILE FORMATS;

DESC FILE FORMAT ingest_csv_data;

CREATE OR REPLACE STAGE stage_employee_v1
URL='s3://empoyee-scd-data/employee_data/'
STORAGE_INTEGRATION = employee_integration
FILE_FORMAT = (FORMAT_NAME = ingest_csv_data);

LIST @stage_employee_v1;

CREATE OR REPLACE TABLE STG_EMPLOYEE
(
EID VARCHAR,
ENAME VARCHAR,
EMAIL VARCHAR,
PHONENO VARCHAR,
Address VARCHAR,
COMPANYNAME VARCHAR,
EXP INT
);

CREATE OR REPLACE TABLE EMPLOYEE_TYPE_1
(
EID VARCHAR,
ENAME VARCHAR,
EMAIL VARCHAR,
PHONENO VARCHAR,
Address VARCHAR,
COMPANYNAME VARCHAR,
EXP INT
);

CREATE OR REPLACE TABLE EMPLOYEE_TYPE_2
(
EID VARCHAR,
ENAME VARCHAR,
EMAIL VARCHAR,
PHONENO VARCHAR,
Address VARCHAR,
COMPANYNAME VARCHAR,
EXP INT,
START_DATE DATE,
END_DATE DATE DEFAULT DATE '2999-12-31',
IS_ACTIVE BOOLEAN
);


CREATE OR REPLACE TASK CLEAN_STAGE_TABLE
WAREHOUSE = COMPUTE_WH
SCHEDULE = '1 MINUTE'
AS
TRUNCATE TABLE STG_EMPLOYEE; 

CREATE OR REPLACE TASK LOAD_STAGE_DATA
WAREHOUSE = COMPUTE_WH
AFTER CLEAN_STAGE_TABLE
AS 
COPY INTO STG_EMPLOYEE FROM @stage_employee_v1;

CREATE OR REPLACE TASK EMP_SCD1_LOAD
WAREHOUSE = COMPUTE_WH
AFTER LOAD_STAGE_DATA
AS
MERGE INTO EMPLOYEE_TYPE_1 emp
USING (
    SELECT * 
    FROM STG_Employee
) src
ON emp.ENAME = src.ENAME
AND emp.EID = src.EID

WHEN MATCHED
AND (
    emp.EMAIL != src.EMAIL
    OR emp.PHONENO != src.PHONENO
    OR emp.Address != src.address
)
THEN
UPDATE SET
    emp.EMAIL = src.EMAIL,
    emp.PHONENO = src.PHONENO,
    emp.Address = src.address

WHEN NOT MATCHED
THEN
INSERT (
    EID,
    ENAME,
    EMAIL,
    PHONENO,
    Address,
    COMPANYNAME,
    EXP
)
VALUES (
    src.EID,
    src.ENAME,
    src.EMAIL,
    src.PHONENO,
    src.Address,
    src.COMPANYNAME,
    src.EXP
);

SELECT * FROM EMPLOYEE_TYPE_1;

SELECT * FROM stg_employee;

TRUNCATE TABLE EMPLOYEE_TYPE_1;

SHOW TASKS;

ALTER TASK CLEAN_STAGE_TABLE SUSPEND;
ALTER TASK LOAD_STAGE_DATA RESUME;
ALTER TASK EMP_SCD1_LOAD RESUME;

SELECT * FROM TABLE(INFORMATION_SCHEMA.TASK_HISTORY());

--- sdc type-2 

CREATE OR REPLACE STREAM STR_EMP 
ON TABLE EMPLOYEE_TYPE_1;

SELECT * FROM STR_EMP;


CREATE OR REPLACE TASK DIM_EMP_LOAD
WAREHOUSE = COMPUTE_WH
AFTER EMP_SCD1_LOAD
WHEN
SYSTEM$STREAM_HAS_DATA('STR_EMP')
AS
MERGE INTO EMPLOYEE_TYPE_2 emp
USING (
    SELECT * 
    FROM STR_EMP
) chk
ON emp.Eid = chk.Eid
AND emp.Address = chk.Address

WHEN MATCHED
AND (chk.metadata$action = 'DELETE')
THEN
UPDATE SET
    End_date = CURRENT_DATE,
    IS_ACTIVE = 'False'

WHEN NOT MATCHED
AND (chk.metadata$action = 'INSERT')
THEN
INSERT (
    Eid,
    EName,
    Email,
    Phoneno,
    Address,
    COMPANYNAME,
    Exp,
    Start_date,
    IS_ACTIVE
)
VALUES (
    chk.Eid,
    chk.EName,
    chk.Email,
    chk.Phoneno,
    chk.Address,
    chk.Companyname,
    chk.Exp,
    CURRENT_DATE,
    'True'
);

ALTER TASK CLEAN_STAGE_TABLE RESUME;
ALTER TASK LOAD_STAGE_DATA RESUME;
ALTER TASK EMP_SCD1_LOAD RESUME;
ALTER TASK DIM_EMP_LOAD RESUME;

SELECT * FROM EMPLOYEE_TYPE_2;

SELECT * FROM TABLE(INFORMATION_SCHEMA.TASK_HISTORY());

