SHOW TABLES;

ALTER TABLE STUDENT_SCORES 
SET DATA_RETENTION_TIME_IN_DAYS=10;

SHOW SCHEMAS;

ALTER SCHEMA STUDENTSCHEMA
SET DATA_RETENTION_TIME_IN_DAYS=10;

 DROP SCHEMA STUDENTSCHEMA;

 DROP TABLE STUDENT_SCORES;

 UNDROP TABLE STUDENT_SCORES;

 SELECT * FROM STUDENT_SCORES;

 SELECT * FROM STUDENT_SCORES AT (OFF_SET => -2000);

 SELECT * FROM STUDENT_SCORES BEFORE (STATEMENT => '');
 
 SELECT * FROM STUDENT_SCORES AT (TIMESTAMP => '');

 SELECT * FROM SNOWFLAKE.ACCOUNT_USAGE.TABLE_STORAGE_METRICS;